
CREATE DATABASE IF NOT EXISTS FORNODE DEFAULT CHARSET utf8 COLLATE utf8_unicode_ci;

USE FORNODE;

DROP TABLE IF EXISTS USER_TB;
CREATE TABLE IF NOT EXISTS USER_TB(
	`NUM` int not null auto_increment,
	`OWNERKEY` varchar(46)DEFAULT NULL,
	`USERID` varchar(46)DEFAULT NULL,
	`PASSWORD` varchar(46)DEFAULT NULL,
	`USERTYPE` int DEFAULT NULL,
	`NAME` varchar(46)DEFAULT NULL,
	`ADDRESS` varchar(46)DEFAULT NULL,
	PRIMARY KEY(num)
	)DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS COWS_TB;
CREATE TABLE IF NOT EXISTS COWS_TB(
	`OWNERKEY` varchar(46) DEFAULT NULL,
	`COWPTR` varchar(46)DEFAULT NULL
	)DEFAULT CHARSET=utf8;

flush privileges;
